sites/verdadeiro/comments/comentarios/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="index"),
]

sites/verdadeiro/comments/comments/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('comentarios.urls'))
]

sites/verdadeiro/comments/comentarios/models.py
from django.db import models

# Create your models here.


class Perguntas(models.Model):
    texto = models.CharField(max_length=200)
    data_pub = models.DateTimeField('data publicada')

    def __str__(self):
        return self.texto


class Respostas(models.Model):
    texto = models.CharField(max_length=200)
    pergunta = models.ForeignKey(Perguntas, on_delete=models.CASCADE)

    def __str__(self):
        return self.texto

sites/verdadeiro/comments/comentarios/views.py
from django.shortcuts import render
from . import models

# Create your views here.


def index(request):
    context = {'y': models.Perguntas.objects.all}
    return render(request, 'comentarios/index.html', context=context)

sites/verdadeiro/comments/comentarios/templates/comentarios/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'comentarios/style.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

sites/verdadeiro/comments/comentarios/templates/comentarios/index.html
{% extends 'comentarios/base.html '%}

{% block title%}Perguntas e Respostas{% endblock%}

{% block content %}
    
    <h1>Perguntas da vida</h1>

    <p>
        <ul>
        'Aqui vão aparecer 5 perguntas e algumas respostas' <br>
        {% for x in y %}
            <li>{{x}} </li>
            {% for n in x.respostas_set.all %}
                {{n}} <br>
            {% endfor %}
        {% endfor %}
        </ul>
    </p>
    <p>
        Faça uma pergunta: <br>
        'botao'
    
    </p>












{% endblock %}